import { AUTH_ENDPOINTS } from './API.Sessao';
import { USERS_ENDPOINTS } from './API.Usuarios';
import { GROUPS_ENDPOINTS } from './API.Grupos';
import { FEED_ENDPOINTS } from './API.Feed';
import { MARKETPLACE_ENDPOINTS } from './API.Marketplace';
import { NOTIFICATIONS_ENDPOINTS } from './API.Notificacoes';
import { PAYMENTS_ENDPOINTS } from './API.Pagamentos';
import { SUPPORT_ENDPOINTS } from './API.Suporte';
import { REELS_ENDPOINTS } from './API.Reels';

const API_ENDPOINTS = {
  AUTH: AUTH_ENDPOINTS,
  USERS: USERS_ENDPOINTS,
  GROUPS: GROUPS_ENDPOINTS,
  FEED: FEED_ENDPOINTS,
  MARKETPLACE: MARKETPLACE_ENDPOINTS,
  NOTIFICATIONS: NOTIFICATIONS_ENDPOINTS,
  PAYMENTS: PAYMENTS_ENDPOINTS,
  SUPPORT: SUPPORT_ENDPOINTS,
  REELS: REELS_ENDPOINTS,
};

export default API_ENDPOINTS;
